feat: Add ImplementationSet event to setImplementation function (SC-13536)
maple-labs/non-transparent-proxy pull request #13
Opened 2023-08-28 18:20 UTC by Preethisenthilkumar

Indexed the parameters - can remove if not needed
_getAddress function to get the old implementation address is gas intensive - can remove if not needed 
@0xfarhaan @JGcarv @vbidin

2023-08-28 23:34 UTC, vbidin requested changes

2023-08-29 08:53 UTC, 0xfarhaan commented on contracts/NonTransparentProxy.sol
> +        emit ImplementationSet(_getAddress(IMPLEMENTATION_SLOT), newImplementation_);
let's move this to be after `_setAddress`

2023-08-29 14:46 UTC, 0xfarhaan approved these changes

2023-08-29 14:52 UTC, JGcarv approved these changes

2023-08-29 14:58 UTC, merged